### ISSUE TITLE
Giving users flexibility in specifying residue numbering

### ISSUE THREAD

**Issue by jchodera** [choderalab/ensembler#39]
(Moved from #35.)

It would be useful to allow users to manually specify their desired residue numbering scheme to be propagated through to Ensembler-generated models.

Currently, the FASTA format is supported for manually-specified sequences, e.g.:
```
>sp|Q08345|610-905
LRFKEKLGEGQFGEVHLCEVDSPQDLVSLDFPLNVRKGHPLLVAVKILRPDATKNARNDF
LKEVKIMSRLKDPNIIRLLGVCVQDDPLCMITDYMENGDLNQFLSAHQLEDKAAEGAPGD
GQAAQGPTISYPMLLHVAAQIASGMRYLATLNFVHRDLATRNCLVGENFTIKIADFGMSR
NLYAGDYYRVQGRAVLPIRWMAWECILMGKFTTASDVWAFGVTLWEVLMLCRAQPFGQLT
DEQVIENAGEFFRDQGRQVYLSRPPACPQGLYELMLRCWSRESEQRPPFSQLHRFL
```
This unfortunately provides no means to specify residue numbering schemes.

Some alternative possibilities exist:

**Specify an initial residue number along with the one-letter-code sequence.**  For example, in YAML:
```
targets:
    DDR1_HUMAN_D0_PROTONATED:
        initial_residue: 610
        sequence: LRFKEKLGEGQFGEVHLCEVDSPQDLVSLDFPLNVRKGHPLLVAVKILRPDATKNARNDFLKEVKIMSRLKDPNIIRLLGVCVQDDPLCMITDYMENGDLNQFLSAHQLEDKAAEGAPGDGQAAQGPTISYPMLLHVAAQIASGMRYLATLNFVHRDLATRNCLVGENFTIKIADFGMSRNLYAGDYYRVQGRAVLPIRWMAWECILMGKFTTASDVWAFGVTLWEVLMLCRAQPFGQLTDEQVIENAGEFFRDQGRQVYLSRPPACPQGLYELMLRCWSRESEQRPPFSQLHRFL
```
**Specify a PDB `SEQRES` and `DBREF` section.**  This would allow the residue index span to be specified, but has a stricter syntax in which the UniProt gene name is expected:
```
DBREF  5BVN A  595   913  UNP    Q08345   DDR1_HUMAN     576    894              
SEQRES   1 A  324  GLY ALA MET GLY SER ALA VAL GLY ASP GLY PRO PRO ARG           
SEQRES   2 A  324  VAL ASP PHE PRO ARG SER ARG LEU ARG PHE LYS GLU LYS           
SEQRES   3 A  324  LEU GLY GLU GLY GLN PHE GLY GLU VAL HIS LEU CYS GLU           
SEQRES   4 A  324  VAL ASP SER PRO GLN ASP LEU VAL SER LEU ASP PHE PRO           
SEQRES   5 A  324  LEU ASN VAL ARG LYS GLY HIS PRO LEU LEU VAL ALA VAL           
SEQRES   6 A  324  LYS ILE LEU ARG PRO ASP ALA THR LYS ASN ALA ARG ASN           
SEQRES   7 A  324  ASP PHE LEU LYS GLU VAL LYS ILE MET SER ARG LEU LYS           
SEQRES   8 A  324  ASP PRO ASN ILE ILE ARG LEU LEU GLY VAL CYS VAL GLN           
SEQRES   9 A  324  ASP ASP PRO LEU CYS MET ILE THR ASP TYR MET GLU ASN           
SEQRES  10 A  324  GLY ASP LEU ASN GLN PHE LEU SER ALA HIS GLN LEU GLU           
SEQRES  11 A  324  ASP LYS ALA ALA GLU GLY ALA PRO GLY ASP GLY GLN ALA           
SEQRES  12 A  324  ALA GLN GLY PRO THR ILE SER TYR PRO MET LEU LEU HIS           
SEQRES  13 A  324  VAL ALA ALA GLN ILE ALA SER GLY MET ARG TYR LEU ALA           
SEQRES  14 A  324  THR LEU ASN PHE VAL HIS ARG ASP LEU ALA THR ARG ASN           
SEQRES  15 A  324  CYS LEU VAL GLY GLU ASN PHE THR ILE LYS ILE ALA ASP           
SEQRES  16 A  324  PHE GLY MET SER ARG ASN LEU TYR ALA GLY ASP TYR TYR           
SEQRES  17 A  324  ARG VAL GLN GLY ARG ALA VAL LEU PRO ILE ARG TRP MET           
SEQRES  18 A  324  ALA TRP GLU CYS ILE LEU MET GLY LYS PHE THR THR ALA           
SEQRES  19 A  324  SER ASP VAL TRP ALA PHE GLY VAL THR LEU TRP GLU VAL           
SEQRES  20 A  324  LEU MET LEU CYS ARG ALA GLN PRO PHE GLY GLN LEU THR           
SEQRES  21 A  324  ASP GLU GLN VAL ILE GLU ASN ALA GLY GLU PHE PHE ARG           
SEQRES  22 A  324  ASP GLN GLY ARG GLN VAL TYR LEU SER ARG PRO PRO ALA           
SEQRES  23 A  324  CYS PRO GLN GLY LEU TYR GLU LEU MET LEU ARG CYS TRP           
SEQRES  24 A  324  SER ARG GLU SER GLU GLN ARG PRO PRO PHE SER GLN LEU           
SEQRES  25 A  324  HIS ARG PHE LEU ALA GLU ASP ALA LEU ASN THR VAL               
```

**Other ideas?**
